FROM solr:6.6.1

USER root

RUN mkdir -p /ossearch-config/conf /ossearch-config-slave/conf&& \
    cp -r /opt/solr/server/solr/configsets/basic_configs/conf /ossearch-config/ && \
    cp -r /opt/solr/server/solr/configsets/basic_configs/conf /ossearch-config-slave/ && \
    rm -rf /ossearch-config/conf/managed-schema /ossearch-config-slave/conf/managed-schema && \
    chown -R solr:solr /ossearch-config /ossearch-config-slave

USER solr

# copy the repository form the previous image
COPY conf /ossearch-config/conf
COPY conf /ossearch-config-slave/conf

