FROM openjdk:8-jdk-buster

RUN apt-get update; \
	apt-get install -y --no-install-recommends ant vim ssh rsync curl build-essential maven; \
	rm -rf /var/lib/apt/lists/*;

ARG NUTCH_VERSION
ARG HADOOP_VERSION
ENV HADOOP_VERSION=$HADOOP_VERSION
ENV NUTCH_HOME=/opt/nutch
ENV HADOOP_HOME=/opt/hadoop

#RUN mkdir -p $HADOOP_HOME \
#    && cd $HADOOP_HOME \
#    && wget -qO- "https://downloads.apache.org/hadoop/common/hadoop-${HADOOP_VERSION}/hadoop-${HADOOP_VERSION}.tar.gz" | tar -zx --strip-components=1

### LOCAL-TESTING ###
ADD hadoop-${HADOOP_VERSION}.tar.gz /opt
RUN mv /opt/hadoop-${HADOOP_VERSION} $HADOOP_HOME
### LOCAL-TESTING ###

RUN mkdir -p $NUTCH_HOME \
    && cd $NUTCH_HOME \
    && wget -qO- "https://archive.apache.org/dist/nutch/${NUTCH_VERSION}/apache-nutch-${NUTCH_VERSION}-src.tar.gz" | tar -zx --strip-components=1

### LOCAL-TESTING ###
#ADD apache-nutch-${NUTCH_VERSION}-src.tar.gz /opt
#RUN mv /opt/apache-nutch-${NUTCH_VERSION} $NUTCH_HOME
### LOCAL-TESTING ###

# Hadoop install (pseudo distributed)
COPY hadoop/etc/hadoop $HADOOP_HOME/etc/hadoop
RUN sed s/HOSTNAME/localhost/ $HADOOP_HOME/etc/hadoop/core-site.xml.template > $HADOOP_HOME/etc/hadoop/core-site.xml \
    && sed -i 's@^export JAVA_HOME=\${JAVA_HOME}@export JAVA_HOME=${JAVA_HOME:-'"$JAVA_HOME"'}@' $HADOOP_HOME/etc/hadoop/hadoop-env.sh \
    && sed -i 's@^# export JAVA_HOME=@export JAVA_HOME=${JAVA_HOME:-'"$JAVA_HOME"'}@' $HADOOP_HOME/etc/hadoop/hadoop-env.sh \
    && grep JAVA_HOME $HADOOP_HOME/etc/hadoop/hadoop-env.sh \
    && mkdir $HADOOP_HOME/logs \
    && chmod a+rxwt $HADOOP_HOME/logs \
    && chown -R root:root $HADOOP_HOME \
    && find $HADOOP_HOME/ -type d -exec chmod a+rx '{}' \; \
    && find $HADOOP_HOME/ -type f -exec chmod a+r '{}' \; \
    && chmod a+x $HADOOP_HOME/sbin/*.sh \
    && chmod a+x $HADOOP_HOME/bin/*

# passwordless ssh
RUN ssh-keygen -t rsa -P '' -f ~/.ssh/id_rsa \
    && cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys \
    && chmod 0600 ~/.ssh/authorized_keys

ENV HDFS_NAMENODE_USER=root
ENV HDFS_DATANODE_USER=root
ENV HDFS_SECONDARYNAMENODE_USER=root
ENV YARN_RESOURCEMANAGER_USER=root
ENV YARN_NODEMANAGER_USER=root
ENV PATH $HADOOP_HOME/bin/:$PATH


## Nutch 1.x install
COPY nutch/conf $NUTCH_HOME/conf
COPY nutch/src/plugin/index-metadata $NUTCH_HOME/src/plugin/index-metadata
COPY nutch/src/plugin/parse-metatags $NUTCH_HOME/src/plugin/parse-metatags
COPY nutch/src/plugin/scoring-similarity $NUTCH_HOME/src/plugin/scoring-similarity

#COPY nutch/conf/index-writers.xml $NUTCH_HOME/conf/index-writers.xml
#RUN sed -i '6 a <property><name>http.agent.name</name><value>Nutch Spider 1.18</value></property>' /opt/nutch/conf/nutch-site.xml

RUN cd $NUTCH_HOME \
    && ant runtime

RUN mkdir $NUTCH_HOME/logs \
    && chmod a+rxwt $NUTCH_HOME/logs \
    && chown -R root:root $NUTCH_HOME \
    && find $NUTCH_HOME/ -type d -exec chmod a+rx '{}' \; \
    && find $NUTCH_HOME/ -type f -exec chmod a+r '{}' \; \
    && chmod a+x $NUTCH_HOME/runtime/local/bin/* \
    && chmod a+x $NUTCH_HOME/runtime/deploy/bin/*

ENV PATH $NUTCH_HOME/runtime/deploy/bin/:$PATH

WORKDIR $NUTCH_HOME

ADD entry-point.sh /
RUN chmod +x /entry-point.sh

ENTRYPOINT ["/entry-point.sh", "-d"]
#CMD tail -f /var/log/dpkg.log