<template>
  <fieldset :disabled="!isEditing">
    <div class="row g-3 mb-3">
      <div class="col-md-6">
        <div class="form-floating">
          <input :value="crawlDbPath" @input="$emit('update:crawlDbPath', $event.target.value)" class="form-control"
                 id="crawlDbPath"
                 required
                 :placeholder="'./' + collectionName + '/db'" disabled>
          <label for="crawlDbPath">Crawl db path (autogenerated)</label>
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-floating">
          <input :value="crawlSeedPath" @input="$emit('update:crawlSeedPath', $event.target.value)" type="text"
                 class="form-control" id="crawlSeedPath"
                 required
                 placeholder="'./'+ collectionName + '/seeds.txt'" disabled>
          <label for="crawlSeedPath" class="form-label">Crawl Seed Path (autogenerated)</label>
        </div>
      </div>
    </div>

    <div class="row g-3 mb-3">
      <div class="col-md-12">
        <ImportAddEditCheckTable
            v-model:tableOptions="tableOptions.seedUrls"
            :tableData="seedUrls"
            @updateTableData="$emit('update:seedUrls', $event)"
            :selected="selected"
            @selected="updateSelected"
            :isEditing="isEditing"
        />
      </div>
    </div>

<!--    <div class="row g-3 mb-3">
      <div class="col-md-12">
        <ImportAddEditCheckSortableTable
            v-model:tableOptions="tableOptions.regexUrlFilters"
            :tableData="regexUrlFilters"
            :isEditing="!isEditing"
            @updateTableData="$emit('update:regexUrlFilters', $event)"
        >
          <template v-slot:caption>
            <caption>For regex URL exclusion patterns the first matching pattern determines whether a URL is included or ignored during indexing. <b class="text-danger">NOTE: Order matters drag rows to achive desired order</b></caption>
          </template>
        </ImportAddEditCheckSortableTable>
      </div>
    </div>-->

    <div class="row g-3 mb-3">
      <div class="col-md-12">
        <ImportAddEditCheckTable
            v-model:tableOptions="tableOptions.includeSiteUrls"
            :tableData="includeSiteUrls"
            @updateTableData="$emit('update:includeSiteUrls', $event)"
            :isEditing="isEditing"
        />
      </div>
    </div>

    <div class="row g-3 mb-3">
      <div class="col-md-12">
        <ImportAddEditCheckTable
            v-model:tableOptions="tableOptions.excludeSiteUrls"
            :tableData="excludeSiteUrls"
            @updateTableData="$emit('update:excludeSiteUrls', $event)"
            :isEditing="isEditing"
        />
      </div>
    </div>

    <div class="row g-3 mb-3">
      <div class="col-md-12">
        <ImportAddEditCheckSortableTable
            v-model:tableOptions="tableOptions.urlExclusionPatterns"
            :tableData="urlExclusionPatterns"
            :isEditing="!isEditing"
            @updateTableData="$emit('update:urlExclusionPatterns', $event)"
        >
          <!--          <template v-slot:caption>
                      <caption>For regex URL exclusion patterns the first matching pattern determines whether a URL is included or ignored during indexing. <b class="text-danger">NOTE: Order matters drag rows to achive desired order</b></caption>
                    </template>-->
        </ImportAddEditCheckSortableTable>
        <p class="mt-1">For regex URL exclusion patterns the first matching pattern determines whether a URL is included or ignored during indexing. <b class="text-danger">NOTE: Order matters drag rows to achive desired order</b></p>
      </div>
    </div>

    <!--    <div class="row g-3 mb-3">
          <div class="col-md-12">
            <ImportAddEditCheckTable
                v-model:tableOptions="tableOptions.urlExclusionPatterns"
                :tableData="urlExclusionPatterns"
                @updateTableData="$emit('update:urlExclusionPatterns', $event)"
                :isEditing="isEditing"
            />
          </div>
        </div>-->

    <div class="row g-3 mb-3">
      <div class="col-md-6">
        <div class="form-check">
          <input class="form-check-input" type="checkbox" :value="useSitemap" :checked="useSitemap"
                 @change="$emit('update:useSitemap', $event.target.checked)"
                 id="useSitemap">
          <label class="form-check-label" for="useSitemap">
            Use Sitemaps (NOTE: http://{host}/sitemaps.xml will be used by default)
          </label>
        </div>
<!--        <div class="form-floating mb-3">
          <input type="text" class="form-control" id="sitemapUrl"
                 :disabled="!useSitemap" placeholder="Sitemap URL" :value="sitemapUrl"
                 @input="$emit('update:sitemapUrl', $event.target.value)">
          <label for="sitemapUrl" class="form-label">Sitemap URL (default <b>{{ sitemapUrlComp }}</b>)</label>
        </div>-->
      </div>
    </div>
    <div v-if="useSitemap" class="row g-3 mb-3">
      <div class="col-md-12">
        <ImportAddEditCheckTable v-if="useSitemap"
                                 v-model:tableOptions="tableOptions.sitemapUrls"
                                 :tableData="sitemapUrls"
                                 @updateTableData="$emit('update:sitemapUrls', $event)"
                                 :selected="selected"
                                 @selected="updateSelected"
                                 :isEditing="isEditing"
        />
      </div>
    </div>
    <div v-if="useSitemap" class="row g-3 mb-3">
      <div class="col-md-12">
        <ImportAddEditCheckTable
            v-model:tableOptions="tableOptions.excludeSitemapUrls"
            :tableData="excludeSitemapUrls"
            @updateTableData="$emit('update:excludeSitemapUrls', $event)"
            :isEditing="isEditing"
        />
      </div>
    </div>
  </fieldset>
</template>

<script>
import ImportAddEditCheckTable from "../forms/ImportAddEditCheckTable";
import ImportAddEditCheckSortableTable from "../forms/ImportAddEditCheckSortableTable";
// import draggable from "vuedraggable"

export default {
  name: "CollectionCrawlConfigurationForm",
  props: ['isEditing', 'seedUrls', 'siteUrl', 'crawlDbPath', 'collectionName', 'crawlSeedPath', 'useSitemap', 'sitemapUrls', 'includeSiteUrls', 'excludeSiteUrls', 'excludeSitemapUrls', 'urlExclusionPatterns', 'regexUrlFilters'],
  components: {
    ImportAddEditCheckTable,
    ImportAddEditCheckSortableTable,
    // draggable
  },
  emits: [
    'addKeymatch',
    'deleteKeymatch',
    'updateKeymatch',
    'includeSiteUrls',
    'excludeSiteUrls',
    'excludeSitemapUrls',
    'regexUrlFilters'
  ],
  data() {
    let patternTypes = [
      {label: 'contains', value: 'contains'},
      {label: 'regex', value: 'regex'}
    ]
    let regexTypes = [
      {label: 'include', value: 'include'},
      {label: 'exclude', value: 'exclude'}
    ]
    return {
      tableOptions: {
        seedUrls: {
          enableImport: true,
          enableAddRow: true,
          enableActions: true,
          columns: [
            {label: 'Seed URL\'s', width: '75%'},
          ]
        },
        sitemapUrls: {
          enableImport: true,
          enableAddRow: true,
          enableActions: true,
          actionDisabledDefaultValues: ['./sitemap.xml (default)'],
          columns: [
            {label: 'Additional Sitemap URL\'s', width: '75%'},
          ]
        },
        includeSiteUrls: {
          enableImport: true,
          enableAddRow: true,
          enableActions: true,
          columns: [
            {label: 'Include Site URL\'s', name: 'siteUrl', width: '75%'}
          ]
        },
        excludeSiteUrls: {
          enableImport: true,
          enableAddRow: true,
          enableActions: true,
          columns: [
            {label: 'Exclude Site URL\'s', name: 'siteUrl', width: '75%'}
          ]
        },
        excludeSitemapUrls: {
          enableImport: true,
          enableAddRow: true,
          enableActions: true,
          columns: [
            {label: 'Exclude Sitemap URL\'s', name: 'sitemapUrl', width: '75%'}
          ]
        },
        urlExclusionPatterns: {
          enableImport: true,
          enableAddRow: true,
          enableActions: true,
          itemKey: '',
          columns: [
            {label: 'URL Exclusion Patterns', name: 'expression', width: '70%'},
            {label: 'Type', name: 'type', class: 'text-center', type: 'select', options: patternTypes, default: "regex", width: '10%'},
            {label: 'Ignore Case', name: 'ignoreCase', type: 'checkbox', class: 'text-center', width: '9%'}
          ]
        },
        regexUrlFilters: {
          enableImport: true,
          enableAddRow: true,
          enableActions: true,
          itemKey: "orderId",
          columns: [
            {label: 'Type', name: 'type', class: 'text-center', type: 'select', options: regexTypes, default: "exclude", width: '10%'},
            {label: 'Regex URL Exclusion Patterns', name: 'expression'},
          ]
        }
      },
      selected: []
    }
  },
  computed: {
    // sitemapUrlComp() {
    //   let url = "./sitemap.xml"
    //   if (this.sitemapUrl !== '') {
    //     url = this.sitemapUrl
    //   } else if (this.siteUrl !== '') {
    //     url = this.siteUrl + "/sitemap.xml"
    //     this.$emit('update:sitemapUrl', url)
    //   }
    //   return url
    // },
    // siteUrls() {
    //   let siteUrls = []
    //   for (let item in this.includeSiteUrls) {
    //     siteUrls.push({siteUrl: this.includeSiteUrls[item], type: 'include'})
    //   }
    //   for (let item in this.excludeSiteUrls) {
    //     siteUrls.push({siteUrl: this.excludeSiteUrls[item], type: 'exclude'})
    //   }
    //   return siteUrls
    // },
    // sitemapUrls() {
    //   let sitemapUrls = []
    //   for (let item in this.includeSitemapUrls) {
    //     sitemapUrls.push({sitemapUrl: this.includeSitemapUrls[item], type: 'include'})
    //   }
    //   for (let item in this.excludeSitemapUrls) {
    //     sitemapUrls.push({sitemapUrl: this.excludeSitemapUrls[item], type: 'exclude'})
    //   }
    //   return sitemapUrls
    // }
  },
  methods: {
    // updateSiteUrls(siteUrls) {
    //   console.log("update: ", siteUrls)
    //   let includeSiteUrls = []
    //   let excludeSiteUrls = []
    //   for (let item in siteUrls) {
    //     if (siteUrls[item].type === 'include') {
    //       includeSiteUrls.push(siteUrls[item].siteUrl)
    //     } else if (siteUrls[item].type === 'exclude') {
    //       excludeSiteUrls.push(siteUrls[item].siteUrl)
    //     }
    //   }
    //   this.$emit('update:includeSiteUrls', includeSiteUrls)
    //   this.$emit('update:excludeSiteUrls', excludeSiteUrls)
    // },
    // updateSitemapUrls(sitemapUrls) {
    //   console.log("update: ", sitemapUrls)
    //   let includeSitemapUrls = []
    //   let excludeSitemapUrls = []
    //   for (let item in sitemapUrls) {
    //     if (sitemapUrls[item].type === 'include') {
    //       includeSitemapUrls.push(sitemapUrls[item].sitemapUrl)
    //     } else if (sitemapUrls[item].type === 'exclude') {
    //       excludeSitemapUrls.push(sitemapUrls[item].sitemapUrl)
    //     }
    //   }
    //   this.$emit('update:includeSitemapUrls', includeSitemapUrls)
    //   this.$emit('update:excludeSitemapUrls', excludeSitemapUrls)
    // },
    updateSelected(event) {
      this.selected = event
    },
    updateOrderId(event) {
      console.log(event)
      let regexUrlFiltersCopy = [...this.regexUrlFilters]
      regexUrlFiltersCopy.forEach((item, i) => {
        item.orderId = i + 1;
      });
      this.$emit('regexUrlFilters', regexUrlFiltersCopy)
    }
  }
}
</script>

<style scoped>

</style>
